
###
GET http://localhost:3000/product-api/products


###
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productName" : "iPhone",
    "price" : 80000,
    "brand" : "Apple"
}



###
GET http://localhost:3000/user-api/users


//create user req
### 
POST http://localhost:3000/user-api/user
Content-Type: application/json

{
    "name" : "abhi",
    "email" : "abhi@gmail.com",
    "password" : "abhi",
    "cart" : []
}


###Auth User
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "name" : "ressy",
    "email" : "reddy@gmail.com",
    "password" : "reddy",
    "cart" : []
}

### add the product into the cart
#PUT http://localhost:3000/user-api/user-cart/user-id/6983575a7db38b1d6d8b4bf3/product-id/6981872c34e8ec563fadedd1



### req to increse the qty product in the cart
PUT http://localhost:3000/user-api/user-cart/user-id/6983578c7db38b1d6d8b4bfc/product-id/6981873e34e8ec563fadedd3



###
GET http://localhost:3000/user-api/users/698072461e38a85fae09aaad
