###get all products
GET http://localhost:5000/product-api/products

###create product
POST http://localhost:5000/product-api/products
Content-Type: application/json

{
    "productName": "Ear buds",
    "price": 5000,
    "brand": "Realme"
}

###get all users
GET http://localhost:5000/user-api/users

###create user 
POST http://localhost:5000/user-api/users
Content-Type: application/json

{
    "name": "Harsha",
    "email": "shobu@gmail.com",
    "password": "shobu@123",
    "cart": []
}

###add product to cart
PUT  http://localhost:5000/user-api/user-cart/user-id/69838b6f6053f4965627ed0f/product-id/69838a5e140cf71875593df9

###Read user by id
GET http://localhost:5000/user-api/users/69838b6f6053f4965627ed0f

###comapring ids
GET http://localhost:5000/user-api/compare/69818a9886d9718fa1ae42c0